name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."

name: Prevent direct push to main

on:
  push:
    branches: [ main ]

jobs:
  prevent-direct-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check if direct push
        run: |
          if [[ `git rev-parse --abbrev-ref HEAD` == origin/main ]]; then
            echo "Direct push to main branch detected!"
          fi
      - name: Post comment if direct push
        if: steps.check-if-direct-push.outputs
        run: |
          git fetch origin
          git checkout main
          git branch --contains HEAD | grep -v origin/main > /tmp/direct-push-branches.txt
          if [[ -s /tmp/direct-push-branches.txt ]]; then
            git checkout HEAD^
            git commit --amend -m "Please submit your changes as a pull request."
            git push origin HEAD
          fi
          git checkout HEAD~
          git commit --amend -m "Direct push detected. Please submit a pull request."
          git push origin HEAD
          git checkout main
